import { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, Calendar, Clock, User } from 'lucide-react';
import Image from 'next/image';
import { notFound } from 'next/navigation';

// Mock data for blog posts
const blogPosts = {
  'omnichannel-performance-marketing-2026': {
    title: 'The 2026 Guide to Omnichannel Performance Marketing',
    category: 'Strategy',
    author: 'Divyam Bajaj',
    date: 'March 8, 2026',
    readTime: '8 min read',
    imageSeed: 'strategy',
    content: `
      <p>In the early days of digital marketing, you could scale a brand on a single channel. Today, relying solely on Meta Ads or Google Search is a recipe for diminishing returns. Siloed marketing channels kill ROAS because they ignore the complex, multi-touch reality of the modern consumer journey.</p>
      
      <h2>What Omnichannel Actually Means in 2026</h2>
      <p>Omnichannel isn't just about being present on every platform. It's about creating a seamless, integrated experience where each channel feeds into and supports the others. It means your messaging, creative, and data strategy are unified across the entire funnel.</p>

      <blockquote>"Brands running 3+ integrated channels see 2.8x higher customer lifetime value than single-channel brands."</blockquote>

      <h2>How SEO, Paid Ads, Social and Creative Work Together</h2>
      <p>When executed correctly, channels act as multipliers. SEO captures high-intent demand generated by your Paid Social awareness campaigns. Google Ads remarketing closes the loop on users who discovered you via organic social. High-performing organic creative is repurposed as paid ad variations. This is the ecosystem approach.</p>

      <h2>The MetaZynx 360° Approach</h2>
      <p>At MetaZynx, we don't operate in silos. Our SEO specialists sit next to our media buyers, and our creative directors review search intent data. This 360° visibility allows us to allocate budget dynamically to the highest-performing touchpoints, rather than artificially propping up failing campaigns.</p>

      <h2>3 Steps to Build a Cohesive Strategy</h2>
      <ul>
        <li><strong>Unify Your Data:</strong> Implement robust tracking (like server-side tagging) to understand the true customer journey across all touchpoints.</li>
        <li><strong>Align Your Messaging:</strong> Ensure your brand voice and core offers are consistent from the first TikTok ad to the final checkout page.</li>
        <li><strong>Test Cross-Channel:</strong> Use insights from one channel to fuel another. Did a specific headline work well in Google Ads? Test it as a hook in your next Meta video ad.</li>
      </ul>
    `
  },
  'future-of-search-ai-overviews': {
    title: 'The Future of Search: AI Overviews and Your Organic Strategy',
    category: 'SEO',
    author: 'Divyam Bajaj',
    date: 'March 5, 2026',
    readTime: '6 min read',
    imageSeed: 'seo',
    content: `
      <p>Search is evolving faster than ever. With the introduction of AI Overviews, traditional SEO strategies are being challenged. Here is how to adapt and thrive in the new landscape.</p>
      <h2>Understanding AI Overviews</h2>
      <p>AI Overviews synthesize information from multiple sources to provide direct answers. To rank, your content must be authoritative, comprehensive, and structured for AI extraction.</p>
      <h2>Adapting Your Strategy</h2>
      <ul>
        <li><strong>Focus on Entity SEO:</strong> Build topical authority around core entities rather than just targeting keywords.</li>
        <li><strong>Provide Unique Value:</strong> AI can summarize facts, but it can't replicate unique insights, original research, or strong opinions.</li>
        <li><strong>Optimize for Long-Tail Queries:</strong> Users are asking more complex, conversational questions. Answer them directly and thoroughly.</li>
      </ul>
    `
  },
  'why-meta-ads-fail': {
    title: 'Why Your Meta Ads Are Failing (And How to Fix Them)',
    category: 'Paid Media',
    author: 'Divyam Bajaj',
    date: 'March 2, 2026',
    readTime: '5 min read',
    imageSeed: 'ads',
    content: `
      <p>Many brands struggle to achieve profitable ROAS on Meta. The problem usually isn't the platform; it's the strategy. Let's break down the most common reasons Meta Ads fail.</p>
      <h2>1. Over-Segmented Account Structures</h2>
      <p>Creating too many ad sets restricts the algorithm's ability to learn. Consolidate your campaigns to feed the machine more data.</p>
      <h2>2. Creative Fatigue</h2>
      <p>Your audience is tired of seeing the same ad. You need a robust creative testing framework to constantly introduce new angles and formats.</p>
      <h2>3. Ignoring the Post-Click Experience</h2>
      <p>A great ad can't fix a terrible landing page. Ensure your post-click experience is optimized for conversion and aligns with the ad's promise.</p>
    `
  },
  'authentic-creator-partnerships': {
    title: 'UGC is Dead. Long Live Authentic Creator Partnerships.',
    category: 'Social Media',
    author: 'Divyam Bajaj',
    date: 'Feb 28, 2026',
    readTime: '7 min read',
    imageSeed: 'social',
    content: `
      <p>The era of highly scripted, fake-looking User-Generated Content (UGC) is over. Consumers crave authenticity. Here's how to build real creator partnerships.</p>
      <h2>The Shift to Authenticity</h2>
      <p>Audiences can spot an ad from a mile away. They want to see real people using products in their actual lives, not actors reading from a script.</p>
      <h2>Building Genuine Partnerships</h2>
      <ul>
        <li><strong>Find Brand Advocates:</strong> Look for creators who already use and love your product.</li>
        <li><strong>Give Creative Freedom:</strong> Trust creators to know their audience best. Provide guidelines, not scripts.</li>
        <li><strong>Focus on Long-Term Relationships:</strong> One-off posts rarely drive significant impact. Build ongoing ambassadorships.</li>
      </ul>
    `
  },
  'core-web-vitals-ecommerce': {
    title: 'Core Web Vitals: The Silent Killer of E-Commerce Conversion Rates',
    category: 'Content',
    author: 'Divyam Bajaj',
    date: 'Feb 24, 2026',
    readTime: '4 min read',
    imageSeed: 'web',
    content: `
      <p>If your e-commerce site is slow, you are losing money. Core Web Vitals are not just an SEO ranking factor; they are a direct indicator of user experience and conversion potential.</p>
      <h2>The Impact of Speed on Sales</h2>
      <p>Studies show that even a one-second delay in page load time can result in a significant drop in conversions. Users expect instant gratification.</p>
      <h2>Optimizing for Core Web Vitals</h2>
      <ul>
        <li><strong>Optimize Images:</strong> Compress and serve images in next-gen formats like WebP.</li>
        <li><strong>Minimize JavaScript:</strong> Defer non-critical scripts and remove unused code.</li>
        <li><strong>Improve Server Response Time:</strong> Use a fast hosting provider and a Content Delivery Network (CDN).</li>
      </ul>
    `
  },
  'protecting-brand-viral-outrage': {
    title: 'Protecting Your Brand in the Age of Viral Outrage',
    category: 'ORM',
    author: 'Divyam Bajaj',
    date: 'Feb 20, 2026',
    readTime: '5 min read',
    imageSeed: 'reputation',
    content: `
      <p>In today's hyper-connected world, a single misstep can lead to viral outrage. Proactive Online Reputation Management (ORM) is essential for protecting your brand equity.</p>
      <h2>The Anatomy of a Crisis</h2>
      <p>Understanding how crises escalate on social media is the first step to mitigating them. Speed and transparency are critical.</p>
      <h2>Building a Resilient Brand</h2>
      <ul>
        <li><strong>Social Listening:</strong> Monitor brand mentions to catch potential issues early.</li>
        <li><strong>Crisis Communication Plan:</strong> Have a clear protocol for responding to negative feedback and PR crises.</li>
        <li><strong>Proactive Positive Content:</strong> Build a strong foundation of positive content to buffer against negative search results.</li>
      </ul>
    `
  },
  'psychology-of-ad-creatives': {
    title: 'Design That Converts: The Psychology of Ad Creatives',
    category: 'Strategy',
    author: 'Divyam Bajaj',
    date: 'Feb 15, 2026',
    readTime: '6 min read',
    imageSeed: 'design',
    content: `
      <p>Great ad creative isn't just about looking good; it's about understanding human psychology. Here is how to design ads that drive action.</p>
      <h2>The Power of Visual Hierarchy</h2>
      <p>Guide the user's eye to the most important elements of your ad: the hook, the value proposition, and the call to action.</p>
      <h2>Psychological Triggers</h2>
      <ul>
        <li><strong>Social Proof:</strong> Use testimonials and reviews to build trust.</li>
        <li><strong>Scarcity and Urgency:</strong> Create a sense of FOMO (Fear Of Missing Out) to encourage immediate action.</li>
        <li><strong>Emotional Appeal:</strong> Connect with your audience on an emotional level to make your brand memorable.</li>
      </ul>
    `
  },
  'technical-seo-mistakes': {
    title: '10 Technical SEO Mistakes Costing You Traffic',
    category: 'SEO',
    author: 'Divyam Bajaj',
    date: 'Jan 12, 2026',
    readTime: '7 min read',
    imageSeed: 'seo',
    content: `
      <p>Even the best content won't rank if your website has underlying technical issues. Here are the most common technical SEO mistakes we see.</p>
      <h2>Common Pitfalls</h2>
      <ul>
        <li><strong>Poor Crawlability:</strong> Ensure search engines can easily access and index your pages.</li>
        <li><strong>Improper Redirects:</strong> Avoid redirect chains and use 301 redirects correctly.</li>
        <li><strong>Duplicate Content:</strong> Use canonical tags to consolidate ranking signals.</li>
      </ul>
    `
  },
  'google-ads-bidding': {
    title: 'The Ultimate Guide to Google Ads Bidding Strategies',
    category: 'Paid Media',
    author: 'Divyam Bajaj',
    date: 'Jan 05, 2026',
    readTime: '9 min read',
    imageSeed: 'ads',
    content: `
      <p>Choosing the right bidding strategy is crucial for Google Ads success. This guide breaks down the different options and when to use them.</p>
      <h2>Manual vs. Automated Bidding</h2>
      <p>Understand the pros and cons of manual control versus leveraging Google's machine learning algorithms.</p>
      <h2>Key Strategies</h2>
      <ul>
        <li><strong>Target CPA:</strong> Optimize for a specific cost per acquisition.</li>
        <li><strong>Target ROAS:</strong> Maximize conversion value based on your target return on ad spend.</li>
        <li><strong>Maximize Conversions:</strong> Get the most conversions possible within your budget.</li>
      </ul>
    `
  },
  'high-converting-landing-page': {
    title: 'How to Build a High-Converting Landing Page',
    category: 'Content',
    author: 'Divyam Bajaj',
    date: 'Dec 28, 2025',
    readTime: '6 min read',
    imageSeed: 'design',
    content: `
      <p>Your landing page is where the magic happens. A poorly designed page will waste your ad spend. Here is how to build a page that converts.</p>
      <h2>Essential Elements</h2>
      <ul>
        <li><strong>A Clear Value Proposition:</strong> Immediately tell the user what they get and why they should care.</li>
        <li><strong>Strong Call to Action:</strong> Make it obvious what the user should do next.</li>
        <li><strong>Frictionless Forms:</strong> Only ask for the information you absolutely need.</li>
      </ul>
    `
  }
};

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const resolvedParams = await params;
  const post = blogPosts[resolvedParams.slug as keyof typeof blogPosts];
  
  if (!post) {
    return {
      title: 'Post Not Found | MetaZynx',
    };
  }

  return {
    title: `${post.title} | MetaZynx Blog`,
    description: post.content.substring(0, 150).replace(/<[^>]*>?/gm, ''),
    alternates: {
      canonical: `https://www.metazynx.com/blog/${resolvedParams.slug}`,
    },
  };
}

export default async function BlogPost({ params }: { params: Promise<{ slug: string }> }) {
  const resolvedParams = await params;
  const post = blogPosts[resolvedParams.slug as keyof typeof blogPosts];

  if (!post) {
    notFound();
  }

  return (
    <main className="min-h-screen bg-primary-bg flex flex-col pt-24">
      {/* Hero Section */}
      <section className="bg-card-bg py-16 md:py-24 border-b border-border-glass relative overflow-hidden">
        <div className="absolute inset-0 bg-grid-pattern opacity-30 z-0 pointer-events-none"></div>
        <div className="max-w-4xl mx-auto px-6 relative z-10 flex flex-col items-center text-center">
          <span className="inline-block bg-primary-text text-primary-bg font-mono font-bold text-[11px] uppercase tracking-[2px] px-4 py-1.5 rounded-full mb-8 shadow-sm">
            {post.category}
          </span>
          <h1 className="font-sans font-black text-[40px] md:text-[56px] leading-[1.1] tracking-tight text-primary-text mb-8">
            {post.title}
          </h1>
          <div className="flex flex-wrap items-center justify-center gap-4 md:gap-8 font-mono text-[13px] text-secondary-text uppercase tracking-[1px]">
            <div className="flex items-center gap-2"><User size={16} className="text-brand-action" /> {post.author}</div>
            <div className="hidden md:block w-1 h-1 rounded-full bg-border-glass"></div>
            <div className="flex items-center gap-2"><Calendar size={16} className="text-brand-action" /> {post.date}</div>
            <div className="hidden md:block w-1 h-1 rounded-full bg-border-glass"></div>
            <div className="flex items-center gap-2"><Clock size={16} className="text-brand-action" /> {post.readTime}</div>
          </div>
        </div>
      </section>

      {/* Featured Image */}
      <section className="max-w-5xl mx-auto px-6 -mt-12 relative z-20 w-full">
        <div className="relative h-[300px] md:h-[500px] w-full rounded-2xl overflow-hidden shadow-2xl border border-border-glass bg-secondary-bg">
          <Image
            src={`https://picsum.photos/seed/${post.imageSeed}/1200/800`}
            alt={post.title}
            fill
            className="object-cover mix-blend-luminosity hover:mix-blend-normal transition-all duration-700"
            referrerPolicy="no-referrer"
            priority
          />
        </div>
      </section>

      {/* Article Body */}
      <section className="py-16 md:py-24 px-6 flex-grow">
        <div className="max-w-3xl mx-auto">
          <div 
            className="prose prose-lg prose-zinc dark:prose-invert max-w-none
              prose-headings:font-sans prose-headings:font-bold prose-headings:tracking-tight prose-headings:text-primary-text
              prose-p:font-sans prose-p:text-secondary-text prose-p:leading-relaxed
              prose-a:text-brand-action prose-a:no-underline hover:prose-a:underline
              prose-strong:text-primary-text prose-strong:font-bold
              prose-blockquote:border-l-brand-action prose-blockquote:bg-card-bg prose-blockquote:px-6 prose-blockquote:py-2 prose-blockquote:rounded-r-lg prose-blockquote:font-sans prose-blockquote:text-primary-text prose-blockquote:not-italic
              prose-ul:text-secondary-text prose-li:marker:text-brand-action"
            dangerouslySetInnerHTML={{ __html: post.content }}
          />
          
          <div className="mt-16 pt-8 border-t border-border-glass flex items-center justify-between">
            <Link 
              href="/blog"
              className="inline-flex items-center gap-2 font-mono text-[13px] font-medium text-secondary-text hover:text-brand-action transition-colors uppercase tracking-[1px]"
            >
              &larr; Back to Blog
            </Link>
            
            <div className="flex gap-4">
              {/* Share buttons could go here */}
            </div>
          </div>
        </div>
      </section>

      {/* Bottom CTA */}
      <section className="bg-card-bg py-24 px-6 text-center border-t border-border-glass relative overflow-hidden">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-brand-action/5 rounded-full blur-3xl pointer-events-none"></div>
        <div className="max-w-3xl mx-auto flex flex-col items-center relative z-10">
          <h2 className="font-sans font-black text-[36px] md:text-[48px] tracking-tight text-primary-text mb-6">
            Ready to scale your revenue?
          </h2>
          <p className="font-sans text-[18px] text-secondary-text mb-10 max-w-xl">
            Stop guessing and start growing. Get a data-driven audit of your current marketing strategy.
          </p>
          <Link 
            href="/contact"
            className="inline-flex items-center justify-center bg-primary-text text-primary-bg font-sans font-bold text-[15px] uppercase tracking-[1.5px] px-8 py-4 rounded-xl hover:bg-brand-action hover:text-white transition-all shadow-sm"
          >
            Get Your Free Audit <ArrowRight size={18} className="ml-2" />
          </Link>
        </div>
      </section>
    </main>
  );
}
