import { Metadata } from 'next';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'The 2026 Guide to Omnichannel Performance Marketing | MetaZynx Blog',
  description: 'Why siloed marketing channels kill ROAS and how to build a cohesive omnichannel strategy in 2026.',
};

export default function BlogPost() {
  return (
    <main className="min-h-screen bg-primary-bg flex flex-col">
      <Navbar />

      {/* Section 1 — Hero */}
      <section className="bg-[#FAFAF8] py-[80px] flex flex-col items-center text-center mt-20">
        <div className="max-w-[780px] mx-auto px-6 flex flex-col items-center">
          <span className="inline-block bg-[#E8440A] text-white font-sans font-bold text-[12px] uppercase tracking-[2px] px-4 py-1.5 rounded-full mb-6">
            STRATEGY
          </span>
          <h1 className="font-display font-extrabold text-[48px] leading-[1.2] text-[#1B2D5B] mb-6">
            The 2026 Guide to Omnichannel Performance Marketing
          </h1>
          <div className="font-sans font-light text-[15px] text-gray-500 flex items-center justify-center gap-2">
            <span>Divyam Bajaj</span>
            <span>•</span>
            <span>March 8, 2026 | 8 min read</span>
          </div>
          <div className="w-[60px] h-[3px] bg-[#E8440A] mx-auto mt-8"></div>
        </div>
      </section>

      {/* Section 2 — Article Body */}
      <section className="bg-white py-[80px] px-[24px] flex-grow">
        <div className="max-w-[740px] mx-auto font-sans font-light text-[18px] text-[#4A4A4A] leading-[1.8] space-y-6">
          <p>
            In the early days of digital marketing, you could scale a brand on a single channel. Today, relying solely on Meta Ads or Google Search is a recipe for diminishing returns. Siloed marketing channels kill ROAS because they ignore the complex, multi-touch reality of the modern consumer journey.
          </p>
          
          <h2 className="font-display font-bold text-[32px] text-[#1B2D5B] mt-12 mb-6">
            What Omnichannel Actually Means in 2026
          </h2>
          <p>
            Omnichannel isn&apos;t just about being present on every platform. It&apos;s about creating a seamless, integrated experience where each channel feeds into and supports the others. It means your messaging, creative, and data strategy are unified across the entire funnel.
          </p>

          <div className="border-l-4 border-[#E8440A] bg-[#FAFAF8] p-6 my-[40px] text-[#1B2D5B]">
            <p className="font-display font-bold text-[20px] m-0 leading-[1.5]">
              &quot;Brands running 3+ integrated channels see 2.8x higher customer lifetime value than single-channel brands.&quot;
            </p>
          </div>

          <h2 className="font-display font-bold text-[32px] text-[#1B2D5B] mt-12 mb-6">
            How SEO, Paid Ads, Social and Creative Work Together
          </h2>
          <p>
            When executed correctly, channels act as multipliers. SEO captures high-intent demand generated by your Paid Social awareness campaigns. Google Ads remarketing closes the loop on users who discovered you via organic social. High-performing organic creative is repurposed as paid ad variations. This is the ecosystem approach.
          </p>

          <h2 className="font-display font-bold text-[32px] text-[#1B2D5B] mt-12 mb-6">
            The MetaZynx 360&deg; Approach
          </h2>
          <p>
            At MetaZynx, we don&apos;t operate in silos. Our SEO specialists sit next to our media buyers, and our creative directors review search intent data. This 360&deg; visibility allows us to allocate budget dynamically to the highest-performing touchpoints, rather than artificially propping up failing campaigns.
          </p>

          <h2 className="font-display font-bold text-[32px] text-[#1B2D5B] mt-12 mb-6">
            3 Steps to Build a Cohesive Strategy
          </h2>
          <ul className="list-disc pl-6 space-y-3 my-6">
            <li><strong>Unify Your Data:</strong> Implement robust tracking (like server-side tagging) to understand the true customer journey across all touchpoints.</li>
            <li><strong>Align Your Messaging:</strong> Ensure your brand voice and core offers are consistent from the first TikTok ad to the final checkout page.</li>
            <li><strong>Test Cross-Channel:</strong> Use insights from one channel to fuel another. Did a specific headline work well in Google Ads? Test it as a hook in your next Meta video ad.</li>
          </ul>
        </div>
      </section>

      {/* Section 3 — Bottom CTA */}
      <section className="bg-[#1B2D5B] py-[80px] px-6 text-center">
        <div className="max-w-3xl mx-auto flex flex-col items-center">
          <h2 className="font-display font-extrabold text-[40px] text-white mb-8">
            Ready to grow your brand?
          </h2>
          <Link 
            href="/contact"
            className="inline-flex items-center justify-center bg-[#E8440A] text-white font-sans font-bold text-[16px] uppercase tracking-[2px] px-10 py-5 rounded-md hover:scale-[1.03] hover:shadow-lg hover:shadow-[#E8440A]/20 transition-all duration-200 ease-out"
          >
            Book Your Free Audit &rarr;
          </Link>
        </div>
      </section>

      <Footer />
    </main>
  );
}
